site_name: 编程笔记
site_description: 开发经验分享
site_author: YuFeng
site_url: https://juemuren.github.io/DevNotes/
repo_name: DevNotes
repo_url: https://github.com/Juemuren/DevNotes
copyright: Copyright &copy; 2025-present <a href="https://github.com/Juemuren">YuFeng</a>

markdown_extensions:
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

theme:
  name: material
  language: zh
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换为深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换为浅色模式

plugins: 
  - search
  - callouts
  - git-revision-date
  - open-in-new-tab
  - minify:
      minify_html: true

nav:
  - 首页: index.md
  - 环境管理: 
    - 环境管理: 环境管理/index.md
    - MSYS: 环境管理/MSYS.md
    - Conda: 环境管理/Conda.md
  - 包管理:
    - 包管理: 包管理/index.md
    - Vcpkg: 包管理/Vcpkg.md
  - 编程语言:
    - 编程语言: 编程语言/index.md
    - Cpp: 编程语言/Cpp.md
    - Python: 编程语言/Python.md
  - 命令行工具:
    - 命令行工具: 命令行工具/index.md
    - Shell: 命令行工具/Shell.md
  - 编辑器:
    - 编辑器: 编辑器/index.md
    - VSCode: 编辑器/VSCode.md
  - 开发框架:
    - 开发框架: 开发框架/index.md
    - YOLO: 开发框架/YOLO.md
  - 嵌入式:
    - 嵌入式: 嵌入式/index.md

extra:
  generator: false
